/*
 * This source file was generated by the Gradle 'init' task
 */
package com.itwasneo

import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.assertThrows
import java.io.FileNotFoundException

class AppTest {
    @Test
    fun appHasAGreeting() {
        val classUnderTest = App()
        assertThrows<FileNotFoundException> { classUnderTest.readInput("")  }
    }
}
